### ISSUE TITLE
Update to Julia 1.8.2

### ISSUE THREAD

**Issue by fingolfin** [julia-vscode/julia-devcontainer#16]
Can we please get Julia 1.8.2 (or very soon: 1.8.3) ? It seems this is still at 1.8.0 which unfortunately crashes for me in my code (due to a bug fixed in 1.8.2)

**Comment by fonsp** [comment]
Fixed by https://github.com/julia-vscode/julia-devcontainer/commit/1dc6fa02bb9fb9e2b856488146a664444039ad24
