### ISSUE TITLE
Generate list of Julia versions automatically

### ISSUE THREAD

**Issue by fonsp** [julia-vscode/julia-devcontainer#17]
I wrote a script that generates [this list](https://github.com/julia-vscode/julia-devcontainer/blob/master/.github/workflows/docker-publish.yml#L48) automatically:

```julia
# ╔═╡ 11aafdd2-7a7d-11ed-3904-bba5770864df
import JSON

# ╔═╡ cb4f3c4e-a648-40c9-9eff-a41da6455520
import YAML

# ╔═╡ 8bb975d8-fb1b-40d2-8293-9a95610c0177
url = "https://julialang-s3.julialang.org/bin/versions.json"

# ╔═╡ 132c6e4f-9d51-4165-a3aa-985c17980fc4
versions = JSON.parse(read(download(url), String))

# ╔═╡ 13d39dd3-dd30-4b6f-960a-42a5c1c3a34b
stables = Dict(v => d for (v,d) in versions if get(d, "stable", false))

# ╔═╡ d46d2977-2268-456a-b6fc-9bf67977be7a
output_set = union!(Set{String}(), (
	let 
		major, minor, patch = split(v, ".")
		
		major == "0" ? () : (v, "$(major).$(minor)", major)
	end
	for (v,d) in stables
)...)

# ╔═╡ 01f93214-b7d1-4e8c-935a-fb54ddadf778
result_vec = sort(collect(output_set))

```

Result:

```julia
45-element Vector{String}:
 "1"
 "1.0"
 "1.0.0"
 "1.0.1"
 "1.0.2"
 "1.0.3"
 "1.0.4"
 "1.0.5"
 "1.1"
 "1.1.0"
 "1.1.1"
 "1.2"
 "1.2.0"
 "1.3"
 "1.3.0"
 "1.3.1"
 "1.4"
 "1.4.0"
 "1.4.1"
 "1.4.2"
 "1.5"
 "1.5.0"
 "1.5.1"
 "1.5.2"
 "1.5.3"
 "1.5.4"
 "1.6"
 "1.6.0"
 "1.6.1"
 "1.6.2"
 "1.6.3"
 "1.6.4"
 "1.6.5"
 "1.6.6"
 "1.6.7"
 "1.7"
 "1.7.0"
 "1.7.1"
 "1.7.2"
 "1.7.3"
 "1.8"
 "1.8.0"
 "1.8.1"
 "1.8.2"
 "1.8.3"
```

If this is useful, we could run it on a schedule. Either: 
- it could be an additional step to the docker-publish.yml action, and we use the output as the matrix value ([suggested here](https://stackoverflow.com/questions/59977364/github-actions-how-use-strategy-matrix-with-script)), or 
- it can be a new action that writes this to a json file that is committed to the repo, and read by the docker-publish.yml script. (I don't think actions can modify the `.github` folder directly without a special token.)

**Comment by davidanthoff** [comment]
I think we should in general deprecate this repo here and move over to https://github.com/JuliaLang/devcontainer-features.
