### ISSUE TITLE
Julia 1.9.0+ not available in devcontainer

### ISSUE THREAD

**Issue by tansongchen** [julia-vscode/julia-devcontainer#21]
Hi, I’ve seen you added 1.9.0 a while ago, but I couldn’t get it from `ghcr.io/julia-vscode/julia-devcontainer`. Maybe the containers failed to build?

**Comment by eitsupi** [comment]
See #19

**Comment by tansongchen** [comment]
> See #19

Just took a look, seems great. Do you have an example of using this new method to write an `devcontainer.json` file?

**Comment by eitsupi** [comment]
> Do you have an example of using this new method to write an `devcontainer.json` file?

I don't know what you are looking for, but [a search](https://github.com/search?q=ghcr.io%2Fjulialang%2Fdevcontainer-features%2Fjulia&type=code) will turn up several repositories that use this. For example, this one.
https://github.com/FriesischScott/UncertaintyQuantification.jl/blob/b3130d5b1e7aa19602b125ad220630cf2fd66b3c/.devcontainer/devcontainer.json

Simply install any version of Julia on any base image.
