### ISSUE TITLE
Deprecate this repo

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-devcontainer#22]
The future is https://github.com/JuliaLang/devcontainer-features, so we should mark this repo here as officially deprecated/no longer maintained. I'm not entirely sure what the best way to do that is? Maybe just update the README? And remove any pointer from the VS Code stuff to this repo and replace them with links to the feature? @eitsupi does that sound right to you?

**Comment by davidanthoff** [comment]
So the story is that essentially https://github.com/JuliaLang/devcontainer-features and https://github.com/JuliaLang/devcontainer-templates will entirely replace the need for this repo here.

Once the latter template repo is up-and-running, we can presumably really deprecate this repo here, i.e. remove it from the old registration for the VS Code UI and then update the README here that things are no longer maintained.

**Comment by eitsupi** [comment]
I think we need to do the following steps:

1. Publish the new Template from https://github.com/JuliaLang/devcontainer-templates
2. Add https://github.com/JuliaLang/devcontainer-templates to the index.
3. Remove the old Template from https://github.com/microsoft/vscode-dev-containers (Like microsoft/vscode-dev-containers#1673)
4. Archive this repo.

https://github.com/microsoft/vscode-dev-containers has been announced that it will be archived in November (microsoft/vscode-dev-containers#1762), so doing this now seems like a good time to do it.

**Comment by 3f6a** [comment]
should this be deprecated then? Sometimes I end up in this repo by mistake.

**Comment by davidanthoff** [comment]
Yes, I think that is right! I just updated the README and will archive this repo next.
