### ISSUE TITLE
1.6.0 release is actually 1.6.0-rc3

### ISSUE THREAD

**Issue by fonsp** [julia-vscode/julia-devcontainer#7]
I used this one as my base for the `.devcontainer` on my project, and I got Julia 1.6.0-rc3:

https://github.com/orgs/julia-vscode/packages/container/julia-devcontainer/1682457?tag=1.6.0

Which is fine with me, but I thought I should report it.

**Comment by davidanthoff** [comment]
Ah, thanks! I just pushed a new update that also adds Julia 1.6.1, and hopefully that will pick-up a more recent 1.6.0 version as well.
