### ISSUE TITLE
Add Julia beta/RC versions?

### ISSUE THREAD

**Issue by oschulz** [julia-vscode/julia-devcontainer#8]
Would it be possible to add Julia beta/RC versions (assuming a corresponding image on https://hub.docker.com/_/julia exists)?

Would be handy to have v1.7.0-beta4 available at the moment, for example.

**Comment by eitsupi** [comment]
FYI, I released a Dev Container Feature to install Julia.
This should allow you to install any version of Julia, including the RC versions, on top of `mcr.microsoft.com/devcontainers/base:debian`, etc.
https://github.com/eitsupi/devcontainer-features/pkgs/container/devcontainer-features%2Fjulia
